name: Unit Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        neovim_version: ["stable", "v0.11.0"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}

      - name: Install Lua
        uses: leso-kn/gh-actions-lua@master
        with:
          luaVersion: "5.1"

      - name: Install Luarocks
        uses: hishamhm/gh-actions-luarocks@master
        with:
          luarocksVersion: "3.12.2"

      - name: Install busted
        run: |
          luarocks install busted

      - name: Run tests
        run: |
          busted
