name: Unit Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Neovim stable version
        run: |
          curl -LO https://github.com/neovim/neovim/releases/download/stable/nvim-linux-x86_64.tar.gz
          tar -xzf nvim-linux-x86_64.tar.gz
          sudo mv nvim-linux-x86_64 /opt/nvim
          echo "/opt/nvim/bin" >> $GITHUB_PATH

      - name: Check neovim version
        run: nvim --version

      - name: Install luarocks & busted
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install busted

      - name: Run tests
        run: |
          busted
